/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EmployeesListImport } from './routes/employees-list'
import { Route as EmployeeDetailImport } from './routes/employee-detail'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const EmployeesListRoute = EmployeesListImport.update({
  path: '/employees-list',
  getParentRoute: () => rootRoute,
} as any)

const EmployeeDetailRoute = EmployeeDetailImport.update({
  path: '/employee-detail',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/employee-detail': {
      id: '/employee-detail'
      path: '/employee-detail'
      fullPath: '/employee-detail'
      preLoaderRoute: typeof EmployeeDetailImport
      parentRoute: typeof rootRoute
    }
    '/employees-list': {
      id: '/employees-list'
      path: '/employees-list'
      fullPath: '/employees-list'
      preLoaderRoute: typeof EmployeesListImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutRoute,
  EmployeeDetailRoute,
  EmployeesListRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/employee-detail",
        "/employees-list"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/employee-detail": {
      "filePath": "employee-detail.tsx"
    },
    "/employees-list": {
      "filePath": "employees-list.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
